### ISSUE TITLE
加个.gitignore喵

### ISSUE THREAD

**Issue by Alex4210987** [southern-bird99/C-Programming-course#1]
btw，这个repo名字有点搞

**Comment by southern-bird99** [comment]
repo名字搞是什么意思




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "southern-bird99/C-Programming-course"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月2日(星期五) 上午10:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[southern-bird99/C-Programming-course] 加个.gitignore喵 (Issue #1)





 
btw，这个repo名字有点搞

**Comment by Alex4210987** [comment]
为什么叫[C-Programming-course](https://github.com/southern-bird99/C-Programming-course)
